// Generated by scripts/parse-n5-vocab.mjs from scripts/data/n5-vocab-source.md.
// Re-run the script after editing the source file instead of hand-editing this file.

export interface VocabWord {
  term: string;
  meaning: string;
}

export interface VocabLesson {
  id: number;
  title: string;
  words: VocabWord[];
}

export const n5Lessons: VocabLesson[] = [
  {
    "id": 1,
    "title": "Con người",
    "words": [
      {
        "term": "わたし（私）",
        "meaning": "Tôi"
      },
      {
        "term": "あなた",
        "meaning": "Bạn, anh, chị,..."
      },
      {
        "term": "あのひと（あの人）",
        "meaning": "Người đó, anh kia, chị kia"
      },
      {
        "term": "あのかた（あの方）",
        "meaning": "Cách nói lịch sự, kính trọng của あのひと"
      },
      {
        "term": "～さん",
        "meaning": "Hậu tố thêm vào sau tên người để thể hiện tính lịch sự"
      },
      {
        "term": "～ちゃん",
        "meaning": "Hậu tố thêm vào sau tên trẻ em thay cho ~さん"
      },
      {
        "term": "だれ",
        "meaning": "Ai đó?"
      },
      {
        "term": "どなた",
        "meaning": "Cách nói lịch sự, kính trọng của だれ"
      },
      {
        "term": "おしごとは？（お仕事は）",
        "meaning": "Công việc của bạn là gì?"
      },
      {
        "term": "きょうし（教師）",
        "meaning": "Giáo viên"
      },
      {
        "term": "せんせい（先生）",
        "meaning": "Giáo viên (khi xưng hô)"
      },
      {
        "term": "かいしゃいん（会社員）",
        "meaning": "Nhân viên công ty"
      },
      {
        "term": "ぎんこういん（銀行員）",
        "meaning": "Nhân viên ngân hàng"
      },
      {
        "term": "いしゃ（医者）",
        "meaning": "Bác sĩ"
      },
      {
        "term": "エンジニア",
        "meaning": "Kỹ sư"
      },
      {
        "term": "ナース",
        "meaning": "Y tá"
      },
      {
        "term": "かしゅ（歌手）",
        "meaning": "Ca sĩ"
      },
      {
        "term": "はいゆう（俳優）",
        "meaning": "Diễn viên"
      },
      {
        "term": "かいしゃ（会社）",
        "meaning": "Công ty"
      },
      {
        "term": "ぎんこう（銀行）",
        "meaning": "Ngân hàng"
      },
      {
        "term": "だいがく（大学）",
        "meaning": "Đại học"
      },
      {
        "term": "ベトナム",
        "meaning": "Việt Nam"
      },
      {
        "term": "ベトナムじん（ベトナム人）",
        "meaning": "Người Việt"
      },
      {
        "term": "ベトナムご（ベトナム語）",
        "meaning": "Tiếng Việt"
      },
      {
        "term": "イギリス",
        "meaning": "Anh"
      },
      {
        "term": "イギリスじん（イギリス人）",
        "meaning": "Người Anh"
      },
      {
        "term": "えいご（英語）",
        "meaning": "Tiếng Anh"
      },
      {
        "term": "アメリカ",
        "meaning": "Mĩ"
      },
      {
        "term": "アメリカじん（アメリカ人）",
        "meaning": "Người Mĩ"
      },
      {
        "term": "ちゅうごく",
        "meaning": "Trung Quốc"
      },
      {
        "term": "ちゅうごくじん（中国人）",
        "meaning": "Người Trung"
      },
      {
        "term": "ちゅうごくご（中国語）",
        "meaning": "Tiếng Trung"
      },
      {
        "term": "かんこく",
        "meaning": "Hàn Quốc"
      },
      {
        "term": "かんこくじん（韓国人）",
        "meaning": "Người Hàn"
      },
      {
        "term": "かんこくご（韓国語）",
        "meaning": "Tiếng Hàn"
      },
      {
        "term": "にほん",
        "meaning": "Nhật Bản"
      },
      {
        "term": "にほんじん（日本人）",
        "meaning": "Người Nhật"
      },
      {
        "term": "にほんご（日本語）",
        "meaning": "Tiếng Nhật"
      },
      {
        "term": "ドイツ",
        "meaning": "Đức"
      },
      {
        "term": "ドイツじん（ドイツ人）",
        "meaning": "Người Đức"
      },
      {
        "term": "ドイツご（ドイツ語）",
        "meaning": "Tiếng Đức"
      }
    ]
  },
  {
    "id": 2,
    "title": "Đồ vật",
    "words": [
      {
        "term": "これ",
        "meaning": "Cái này (gần người nói)"
      },
      {
        "term": "この～",
        "meaning": "~ này (gần người nói)"
      },
      {
        "term": "それ",
        "meaning": "Cái đó (gần người nghe)"
      },
      {
        "term": "その～",
        "meaning": "~ đó (gần người nghe)"
      },
      {
        "term": "あれ",
        "meaning": "Cái kia (xa cả hai)"
      },
      {
        "term": "あの～",
        "meaning": "~ kia (xa cả hai)"
      },
      {
        "term": "かさ",
        "meaning": "Ô, dù"
      },
      {
        "term": "かばん",
        "meaning": "Túi sách, cặp"
      },
      {
        "term": "ノート",
        "meaning": "Vở"
      },
      {
        "term": "ほん（本）",
        "meaning": "Sách"
      },
      {
        "term": "てちょう（手帳）",
        "meaning": "Sổ tay"
      },
      {
        "term": "えんぴつ",
        "meaning": "Bút chì"
      },
      {
        "term": "ポールペン",
        "meaning": "Bút bi"
      },
      {
        "term": "シャールペン",
        "meaning": "Bút chì kim"
      },
      {
        "term": "カード",
        "meaning": "Thẻ"
      },
      {
        "term": "かぎ",
        "meaning": "Chìa khóa"
      },
      {
        "term": "とけい（時計）",
        "meaning": "Đồng hồ"
      },
      {
        "term": "めいし（名詞）",
        "meaning": "Danh thiếp"
      },
      {
        "term": "ふでばこ",
        "meaning": "Hộp bút"
      },
      {
        "term": "けしゴム（消しゴム）",
        "meaning": "Cục gôm"
      },
      {
        "term": "おかね（お金）",
        "meaning": "Tiền"
      },
      {
        "term": "けいたいでんわ（携帯電話）",
        "meaning": "Điện thoại di động"
      },
      {
        "term": "じしょ（辞書）",
        "meaning": "Từ điển"
      },
      {
        "term": "ざっし（雑誌）",
        "meaning": "Tạp chí"
      },
      {
        "term": "しんぶん（新聞）",
        "meaning": "Báo"
      },
      {
        "term": "つくえ（机）",
        "meaning": "Bàn"
      },
      {
        "term": "いす",
        "meaning": "Ghế"
      },
      {
        "term": "テレビ",
        "meaning": "Ti vi"
      },
      {
        "term": "コンピューター",
        "meaning": "Máy tính"
      },
      {
        "term": "パソコン",
        "meaning": "Laptop"
      },
      {
        "term": "カメラ",
        "meaning": "Máy ảnh"
      },
      {
        "term": "くるま（車）",
        "meaning": "Ô tô, xe hơi"
      },
      {
        "term": "チョコレート",
        "meaning": "Sô cô la"
      },
      {
        "term": "コーヒー",
        "meaning": "Cà phê"
      },
      {
        "term": "バイク",
        "meaning": "Xe máy"
      },
      {
        "term": "おみやげ（お土産）",
        "meaning": "Quà tặng"
      },
      {
        "term": "なに（何）",
        "meaning": "Cái gì"
      },
      {
        "term": "あのう",
        "meaning": "À, ờ (biểu thị ngại ngùng, do dự)"
      },
      {
        "term": "どうぞ",
        "meaning": "Xin mời (mời ai đó ăn gì)"
      },
      {
        "term": "これからお世話になります",
        "meaning": "Từ nay tôi rất mong sự giúp đỡ của anh chị"
      }
    ]
  },
  {
    "id": 3,
    "title": "Địa điểm",
    "words": [
      {
        "term": "ここ",
        "meaning": "Chỗ này, đây"
      },
      {
        "term": "こちら",
        "meaning": "Cách nói lịch sự của ここ"
      },
      {
        "term": "そこ",
        "meaning": "Chỗ đó"
      },
      {
        "term": "そちら",
        "meaning": "Cách nói lịch sự của そこ"
      },
      {
        "term": "あそこ",
        "meaning": "Chỗ kia"
      },
      {
        "term": "あちら",
        "meaning": "Cách nói lịch sự của あそこ"
      },
      {
        "term": "どこ",
        "meaning": "Chỗ nào, đâu"
      },
      {
        "term": "どちら",
        "meaning": "Cách nói lịch sự của どこ"
      },
      {
        "term": "［お］くに（国）",
        "meaning": "Nước, quốc gia (của người nghe)"
      },
      {
        "term": "うち・いえ（家）",
        "meaning": "Nhà"
      },
      {
        "term": "デパート",
        "meaning": "Trung tâm thương mại"
      },
      {
        "term": "きょうしつ（教室）",
        "meaning": "Phòng học"
      },
      {
        "term": "しょくどう（食堂）",
        "meaning": "Nhà ăn"
      },
      {
        "term": "じむしょ（事務所）",
        "meaning": "Văn phòng"
      },
      {
        "term": "かいぎしつ（会議室）",
        "meaning": "Phòng họp"
      },
      {
        "term": "へや（部屋）",
        "meaning": "Căn phòng"
      },
      {
        "term": "うけつけ（受付）",
        "meaning": "Quầy lễ tân"
      },
      {
        "term": "ロビー",
        "meaning": "Đại sảnh"
      },
      {
        "term": "トイレ／おてあらい（お手洗い）",
        "meaning": "Nhà vệ sinh"
      },
      {
        "term": "うりば（売り場）",
        "meaning": "Quầy bán đồ"
      },
      {
        "term": "ちゅうしゃじょう（駐車場）",
        "meaning": "Bãi đỗ xe"
      },
      {
        "term": "スーパー",
        "meaning": "Siêu thị"
      },
      {
        "term": "かいだん（階段）",
        "meaning": "Cầu thang"
      },
      {
        "term": "エレベーター",
        "meaning": "Thang máy"
      },
      {
        "term": "エスカレーター",
        "meaning": "Thang cuốn"
      },
      {
        "term": "じどうはんばいき（自動販売機）",
        "meaning": "Máy bán hàng tự động"
      },
      {
        "term": "でんわ（電話）・スマホ",
        "meaning": "Điện thoại / Smartphone"
      },
      {
        "term": "くつ",
        "meaning": "Giày"
      },
      {
        "term": "ネクタイ",
        "meaning": "Cà vạt"
      },
      {
        "term": "ワイン",
        "meaning": "Rượu vang"
      },
      {
        "term": "なんがいですか",
        "meaning": "Tầng mấy?"
      },
      {
        "term": "いくらですか",
        "meaning": "Bao nhiêu tiền?"
      },
      {
        "term": "すみません",
        "meaning": "Xin lỗi / Cảm ơn"
      },
      {
        "term": "どうも",
        "meaning": "Cảm ơn"
      },
      {
        "term": "いらっしゃいませ",
        "meaning": "Xin chào quý khách"
      },
      {
        "term": "～「を」ください",
        "meaning": "Cho tôi (~)"
      },
      {
        "term": "～「を」見せてください",
        "meaning": "Hãy cho tôi xem (~)"
      }
    ]
  },
  {
    "id": 4,
    "title": "Thời gian",
    "words": [
      {
        "term": "デパート",
        "meaning": "Trung tâm thương mại"
      },
      {
        "term": "ぎんこう（銀行）",
        "meaning": "Ngân hàng"
      },
      {
        "term": "ゆうびんきょく（郵便局）",
        "meaning": "Bưu điện"
      },
      {
        "term": "びじゅつかん（美術館）",
        "meaning": "Bảo tàng mỹ thuật"
      },
      {
        "term": "としょかん（図書館）",
        "meaning": "Thư viện"
      },
      {
        "term": "がっこう（学校）",
        "meaning": "Trường học"
      },
      {
        "term": "おきます（起きます）",
        "meaning": "Dậy, thức dậy"
      },
      {
        "term": "ねます（寝ます）",
        "meaning": "Ngủ, đi ngủ"
      },
      {
        "term": "はたらきます（働きます）",
        "meaning": "Làm việc"
      },
      {
        "term": "べんきょうします（勉強します）",
        "meaning": "Học"
      },
      {
        "term": "おわります（終わります）",
        "meaning": "Hết, kết thúc, xong"
      },
      {
        "term": "いま（今）",
        "meaning": "Bây giờ"
      },
      {
        "term": "～じ（～時）",
        "meaning": "~ Giờ"
      },
      {
        "term": "～ふん、ぶん（～分）",
        "meaning": "~ Phút"
      },
      {
        "term": "はん（半）",
        "meaning": "Rưỡi, nửa"
      },
      {
        "term": "なんじ",
        "meaning": "Mấy giờ?"
      },
      {
        "term": "なんぷん",
        "meaning": "Mấy phút?"
      },
      {
        "term": "ごぜん（午前）",
        "meaning": "Sáng (trước 12h trưa)"
      },
      {
        "term": "ごご（午後）",
        "meaning": "Chiều (sau 12h trưa)"
      },
      {
        "term": "あさ（朝）",
        "meaning": "Buổi sáng"
      },
      {
        "term": "ひる（昼）",
        "meaning": "Buổi trưa"
      },
      {
        "term": "ばん（晩）",
        "meaning": "Buổi tối"
      },
      {
        "term": "おととい",
        "meaning": "Hôm kia"
      },
      {
        "term": "きのう",
        "meaning": "Hôm qua"
      },
      {
        "term": "きょう",
        "meaning": "Hôm nay"
      },
      {
        "term": "あした",
        "meaning": "Ngày mai"
      },
      {
        "term": "あさって",
        "meaning": "Ngày kia, ngày mốt"
      },
      {
        "term": "けさ",
        "meaning": "Sáng nay"
      },
      {
        "term": "こんばん（今晩）",
        "meaning": "Tối nay"
      },
      {
        "term": "ゆうべ（夕べ）",
        "meaning": "Tối qua"
      },
      {
        "term": "やすみ（休み）",
        "meaning": "Nghỉ"
      },
      {
        "term": "やすみひ（休み日）",
        "meaning": "Ngày nghỉ"
      },
      {
        "term": "ひるやすみ（昼休み）",
        "meaning": "Nghỉ trưa"
      },
      {
        "term": "まいあさ（毎朝）",
        "meaning": "Mỗi sáng"
      },
      {
        "term": "まいばん（毎晩）",
        "meaning": "Mỗi tối"
      },
      {
        "term": "まいにち（毎日）",
        "meaning": "Mỗi ngày"
      },
      {
        "term": "げつようび（月曜日）",
        "meaning": "Thứ hai"
      },
      {
        "term": "かようび（火曜日）",
        "meaning": "Thứ ba"
      },
      {
        "term": "すいようび（水曜日）",
        "meaning": "Thứ tư"
      },
      {
        "term": "もくようび（木曜日）",
        "meaning": "Thứ năm"
      },
      {
        "term": "きんようび（金曜日）",
        "meaning": "Thứ sáu"
      },
      {
        "term": "どようび（土曜日）",
        "meaning": "Thứ bảy"
      },
      {
        "term": "にちようび（日曜日）",
        "meaning": "Chủ nhật"
      },
      {
        "term": "しけん（試験）",
        "meaning": "Kì thi"
      },
      {
        "term": "テスト",
        "meaning": "Kiểm tra"
      },
      {
        "term": "かいぎ（会議）",
        "meaning": "Cuộc họp, hội nghị"
      },
      {
        "term": "えいが（映画）",
        "meaning": "Phim điện ảnh"
      }
    ]
  },
  {
    "id": 5,
    "title": "Phương tiện đi lại",
    "words": [
      {
        "term": "いきます（行きます）",
        "meaning": "Đi"
      },
      {
        "term": "きます（来ます）",
        "meaning": "Đến"
      },
      {
        "term": "かえります（帰ります）",
        "meaning": "Về"
      },
      {
        "term": "がっこう（学校）",
        "meaning": "Trường học"
      },
      {
        "term": "スーパー",
        "meaning": "Siêu thị"
      },
      {
        "term": "えき（駅）",
        "meaning": "Ga, nhà ga"
      },
      {
        "term": "ひこうき（飛行機）",
        "meaning": "Máy bay"
      },
      {
        "term": "ふね（船）",
        "meaning": "Thuyền"
      },
      {
        "term": "でんしゃ（電車）",
        "meaning": "Xe điện"
      },
      {
        "term": "ちかてつ（地下鉄）",
        "meaning": "Tàu điện ngầm"
      },
      {
        "term": "しんかんせん（新幹線）",
        "meaning": "Tàu Shinkansen"
      },
      {
        "term": "バス",
        "meaning": "Xe buýt"
      },
      {
        "term": "タクシー",
        "meaning": "Taxi"
      },
      {
        "term": "じてんしゃ（自転車）",
        "meaning": "Xe đạp"
      },
      {
        "term": "あるいて（歩いて）",
        "meaning": "Đi bộ"
      },
      {
        "term": "ひと（人）",
        "meaning": "Người"
      },
      {
        "term": "ともだち（友達）",
        "meaning": "Bạn, bạn bè"
      },
      {
        "term": "かれ（彼）",
        "meaning": "Anh ấy/ Bạn trai"
      },
      {
        "term": "かのじょ（彼女）",
        "meaning": "Cô ấy/ Bạn gái"
      },
      {
        "term": "かぞく（家族）",
        "meaning": "Gia đình"
      },
      {
        "term": "ひとりで（一人で）",
        "meaning": "Một mình"
      },
      {
        "term": "せんしゅう－こんしゅう－らいしゅう（先週-今週-来週）",
        "meaning": "Tuần trước – Tuần này – Tuần sau"
      },
      {
        "term": "せんげつ－こんげつ－らいげつ（先月-今月-来月）",
        "meaning": "Tháng trước – Tháng này – Tháng sau"
      },
      {
        "term": "きょねん－ことし－らいねん（去年-今年-来年）",
        "meaning": "Năm ngoái – Năm nay – Sang năm"
      },
      {
        "term": "～ねん（年）",
        "meaning": "Năm ~ ；なんねん（何年）Mấy năm? Năm nào?"
      },
      {
        "term": "～がつ（月）",
        "meaning": "Tháng ~ ；なんがつ（何月）Tháng mấy?"
      },
      {
        "term": "ついたち（一日）",
        "meaning": "Ngày mùng 1"
      },
      {
        "term": "ふつか（二日）",
        "meaning": "Ngày mùng 2"
      },
      {
        "term": "みっか（三日）",
        "meaning": "Ngày mùng 3"
      },
      {
        "term": "よっか（四日）",
        "meaning": "Ngày mùng 4"
      },
      {
        "term": "いつか（五日）",
        "meaning": "Ngày mùng 5"
      },
      {
        "term": "むいか（六日）",
        "meaning": "Ngày mùng 6"
      },
      {
        "term": "なのか（七日）",
        "meaning": "Ngày mùng 7"
      },
      {
        "term": "ようか（八日）",
        "meaning": "Ngày mùng 8"
      },
      {
        "term": "ここのか（九日）",
        "meaning": "Ngày mùng 9"
      },
      {
        "term": "とおか（十日）",
        "meaning": "Ngày mùng mười"
      },
      {
        "term": "じゅうよっか（十四日）",
        "meaning": "Ngày 14"
      },
      {
        "term": "はつか（二十日）",
        "meaning": "Ngày 20"
      },
      {
        "term": "にじゅうよっか（二十四日）",
        "meaning": "Ngày 24"
      },
      {
        "term": "～にち（～日）",
        "meaning": "Ngày ~"
      },
      {
        "term": "たんじょうび（誕生日）",
        "meaning": "Sinh nhật"
      },
      {
        "term": "そうですね",
        "meaning": "Ừ nhỉ!"
      }
    ]
  },
  {
    "id": 6,
    "title": "Đồ ăn, thức uống",
    "words": [
      {
        "term": "たべます（食べます）",
        "meaning": "Ăn"
      },
      {
        "term": "のみます（飲みます）",
        "meaning": "Uống"
      },
      {
        "term": "「タバコを」すいます",
        "meaning": "Hút (thuốc)"
      },
      {
        "term": "みます（見ます）",
        "meaning": "Nhìn, xem"
      },
      {
        "term": "ききます（聞きます）",
        "meaning": "Nghe"
      },
      {
        "term": "よみます（読みます）",
        "meaning": "Đọc"
      },
      {
        "term": "かきます（書きます）",
        "meaning": "Viết"
      },
      {
        "term": "いいます（言います）",
        "meaning": "Nói"
      },
      {
        "term": "かいます（買います）",
        "meaning": "Mua"
      },
      {
        "term": "「しゃしんを」とります／「写真を」とります",
        "meaning": "Chụp (hình)"
      },
      {
        "term": "します",
        "meaning": "Làm/ Chơi"
      },
      {
        "term": "「ともだちに」あいます／「友達に」会います",
        "meaning": "Gặp (bạn)"
      },
      {
        "term": "ごはん（ご飯）",
        "meaning": "Cơm/ Bữa cơm"
      },
      {
        "term": "あさごはん（朝ご飯）",
        "meaning": "Bữa sáng"
      },
      {
        "term": "ひるごはん（昼ご飯）",
        "meaning": "Bữa trưa"
      },
      {
        "term": "ばんごはん（晩ご飯）",
        "meaning": "Bữa tối"
      },
      {
        "term": "パン",
        "meaning": "Bánh mì"
      },
      {
        "term": "たまご",
        "meaning": "Trứng"
      },
      {
        "term": "さかな（魚）",
        "meaning": "Cá"
      },
      {
        "term": "やさい（野菜）",
        "meaning": "Rau"
      },
      {
        "term": "にく（肉）",
        "meaning": "Thịt"
      },
      {
        "term": "くだもの（果物）",
        "meaning": "Trái cây"
      },
      {
        "term": "みず（水）",
        "meaning": "Nước"
      },
      {
        "term": "ジュース",
        "meaning": "Nước trái cây"
      },
      {
        "term": "おちゃ（お茶）",
        "meaning": "Trà"
      },
      {
        "term": "ビール",
        "meaning": "Bia"
      },
      {
        "term": "こうちゃ（紅茶）",
        "meaning": "Hồng trà, trà đen"
      },
      {
        "term": "おさけ（お酒）",
        "meaning": "Rượu"
      },
      {
        "term": "ぎゅうにゅう（牛乳）／ミルク",
        "meaning": "Sữa"
      },
      {
        "term": "タバコ",
        "meaning": "Thuốc lá"
      },
      {
        "term": "てがみ（手紙）",
        "meaning": "Thư"
      },
      {
        "term": "レポート",
        "meaning": "Báo cáo"
      },
      {
        "term": "しゃしん（写真）",
        "meaning": "Hình ảnh"
      },
      {
        "term": "ビデオ",
        "meaning": "Video"
      },
      {
        "term": "みせ（店）",
        "meaning": "Cửa hàng"
      },
      {
        "term": "にわ（庭）",
        "meaning": "Khu vườn"
      },
      {
        "term": "しゅくだい（宿題）（をします）",
        "meaning": "(Làm) bài tập"
      },
      {
        "term": "テニス（をします）",
        "meaning": "(Chơi) tennis"
      },
      {
        "term": "サッカー（をします）",
        "meaning": "(Chơi) đá bóng"
      },
      {
        "term": "おはなみ（お花見）",
        "meaning": "Ngắm hoa"
      },
      {
        "term": "なに（何）",
        "meaning": "Cái gì?"
      },
      {
        "term": "いっしょに（一緒に）",
        "meaning": "Cùng nhau"
      },
      {
        "term": "ちょっと",
        "meaning": "Một chút"
      },
      {
        "term": "いつも",
        "meaning": "Luôn luôn, lúc nào cũng"
      },
      {
        "term": "ときどき",
        "meaning": "Thỉnh thoảng"
      },
      {
        "term": "それから",
        "meaning": "Sau đó, tiếp theo"
      },
      {
        "term": "いいですね",
        "meaning": "Được đấy nhỉ/ hay quá"
      },
      {
        "term": "わかりました",
        "meaning": "Tôi hiểu rồi"
      },
      {
        "term": "じゃ、また",
        "meaning": "Gặp sau nhé"
      }
    ]
  },
  {
    "id": 7,
    "title": "Văn phòng phẩm",
    "words": [
      {
        "term": "きります（切ります）",
        "meaning": "Cắt"
      },
      {
        "term": "おくります（送ります）",
        "meaning": "Gửi"
      },
      {
        "term": "あげます",
        "meaning": "Cho, tặng"
      },
      {
        "term": "もらいます",
        "meaning": "Nhận"
      },
      {
        "term": "かします（貸します）",
        "meaning": "Cho mượn, cho vay"
      },
      {
        "term": "かります（借ります）",
        "meaning": "Mượn, vay"
      },
      {
        "term": "おしえます（教えます）",
        "meaning": "Dạy"
      },
      {
        "term": "ならいます（習います）",
        "meaning": "Học tập"
      },
      {
        "term": "（でんわを）かけます／（電話を）かけます",
        "meaning": "Gọi (điện thoại)"
      },
      {
        "term": "て（手）",
        "meaning": "Tay"
      },
      {
        "term": "はし",
        "meaning": "Đũa"
      },
      {
        "term": "スプーン",
        "meaning": "Thìa"
      },
      {
        "term": "ナイフ",
        "meaning": "Dao"
      },
      {
        "term": "フォーク",
        "meaning": "Dĩa, nĩa"
      },
      {
        "term": "はさみ",
        "meaning": "Kéo"
      },
      {
        "term": "パソコン",
        "meaning": "Laptop"
      },
      {
        "term": "ケータイ",
        "meaning": "Điện thoại di động"
      },
      {
        "term": "メール",
        "meaning": "Mail"
      },
      {
        "term": "ねんがじょう（年賀状）",
        "meaning": "Thiệp mừng năm mới"
      },
      {
        "term": "パンチ",
        "meaning": "Cái đục lỗ"
      },
      {
        "term": "ホッチキス",
        "meaning": "Cái dập ghim"
      },
      {
        "term": "セロテープ",
        "meaning": "Băng dính"
      },
      {
        "term": "けしゴム（消しゴム）",
        "meaning": "Cục tẩy"
      },
      {
        "term": "かみ（紙）",
        "meaning": "Giấy"
      },
      {
        "term": "はな（花）",
        "meaning": "Hoa"
      },
      {
        "term": "シャツ",
        "meaning": "Áo sơ mi"
      },
      {
        "term": "プレゼン",
        "meaning": "Quà tặng"
      },
      {
        "term": "にもつ（荷物）",
        "meaning": "Đồ đạc, hành lý"
      },
      {
        "term": "おかね（お金）",
        "meaning": "Tiền"
      },
      {
        "term": "きっぷ（切符）",
        "meaning": "Vé (tàu, xe,...)"
      },
      {
        "term": "クリスマス",
        "meaning": "Giáng sinh"
      },
      {
        "term": "ちち（父）／おとうさん（お父さん）",
        "meaning": "Bố (của mình) / Bố (người khác, khi gọi bố mình)"
      },
      {
        "term": "はは（母）／おかあさん（お母さん）",
        "meaning": "Mẹ (của mình) / Mẹ (người khác, khi gọi mẹ mình)"
      },
      {
        "term": "もう",
        "meaning": "Đã, rồi"
      },
      {
        "term": "まだ",
        "meaning": "Vẫn (chưa, còn)"
      },
      {
        "term": "これから",
        "meaning": "Sau đó, từ bây giờ"
      }
    ]
  },
  {
    "id": 8,
    "title": "Tính từ",
    "words": [
      {
        "term": "ハンサム「な」",
        "meaning": "Đẹp trai"
      },
      {
        "term": "きれい「な」",
        "meaning": "Đẹp, sạch sẽ"
      },
      {
        "term": "しずか「な」（静かな）",
        "meaning": "Yên tĩnh"
      },
      {
        "term": "にぎやか「な」",
        "meaning": "Náo nhiệt"
      },
      {
        "term": "ゆうめい「な」（有名な）",
        "meaning": "Nổi tiếng"
      },
      {
        "term": "しんせつ「な」（親切な）",
        "meaning": "Thân thiện"
      },
      {
        "term": "げんき「な」",
        "meaning": "Khỏe mạnh"
      },
      {
        "term": "ひま「な」",
        "meaning": "Rảnh"
      },
      {
        "term": "べんり「な」",
        "meaning": "Tiện lợi"
      },
      {
        "term": "すてき「な」",
        "meaning": "Tuyệt vời"
      },
      {
        "term": "おおきい（大きい）",
        "meaning": "Lớn"
      },
      {
        "term": "ちいさい（小さい）",
        "meaning": "Nhỏ"
      },
      {
        "term": "あたらしい（新しい）",
        "meaning": "Mới"
      },
      {
        "term": "ふるい（古い）",
        "meaning": "Cũ"
      },
      {
        "term": "いい（よい）",
        "meaning": "Tốt"
      },
      {
        "term": "わるい（悪い）",
        "meaning": "Xấu"
      },
      {
        "term": "あつい（暑い）",
        "meaning": "Nóng (thời tiết)"
      },
      {
        "term": "あつい（熱い）",
        "meaning": "Nóng (cảm giác)"
      },
      {
        "term": "さむい（寒い）",
        "meaning": "Lạnh (thời tiết)"
      },
      {
        "term": "つめたい（冷たい）",
        "meaning": "Lạnh (cảm giác)"
      },
      {
        "term": "むずかしい（難しい）",
        "meaning": "Khó"
      },
      {
        "term": "やさしい",
        "meaning": "Dễ"
      },
      {
        "term": "たかい（高い）",
        "meaning": "Đắt"
      },
      {
        "term": "やすい（安い）",
        "meaning": "Rẻ"
      },
      {
        "term": "たかい（高い）",
        "meaning": "Cao"
      },
      {
        "term": "ひくい（低い）",
        "meaning": "Thấp"
      },
      {
        "term": "おもしろい",
        "meaning": "Thú vị"
      },
      {
        "term": "おいしい",
        "meaning": "Ngon"
      },
      {
        "term": "いそがしい（忙しい）",
        "meaning": "Bận"
      },
      {
        "term": "たのしい（楽しい）",
        "meaning": "Vui"
      },
      {
        "term": "しろい（白い）",
        "meaning": "Trắng"
      },
      {
        "term": "くろい（黒い）",
        "meaning": "Đen"
      },
      {
        "term": "あかい（赤い）",
        "meaning": "Đỏ"
      },
      {
        "term": "あおい（青い）",
        "meaning": "Xanh"
      },
      {
        "term": "さくら（桜）",
        "meaning": "Hoa anh đào"
      },
      {
        "term": "やま（山）",
        "meaning": "Núi"
      },
      {
        "term": "まち（町）",
        "meaning": "Phố, thị trấn"
      },
      {
        "term": "ところ",
        "meaning": "Nơi, điểm"
      },
      {
        "term": "たべもの（食べ物）",
        "meaning": "Đồ ăn"
      },
      {
        "term": "りょう（寮）",
        "meaning": "Ký túc xá"
      },
      {
        "term": "レストラン",
        "meaning": "Nhà hàng"
      },
      {
        "term": "せいかつ（生活）",
        "meaning": "Cuộc sống"
      },
      {
        "term": "とても",
        "meaning": "Rất là"
      },
      {
        "term": "あまり～ない",
        "meaning": "Không (lắm)"
      },
      {
        "term": "そして",
        "meaning": "Và, thêm nữa"
      }
    ]
  },
  {
    "id": 9,
    "title": "Sở thích",
    "words": [
      {
        "term": "わかります",
        "meaning": "Hiểu, nắm được"
      },
      {
        "term": "あります",
        "meaning": "Có (sở hữu)"
      },
      {
        "term": "すき「な」（好きな）",
        "meaning": "Thích"
      },
      {
        "term": "きらい「な」（嫌いな）",
        "meaning": "Ghét, không thích"
      },
      {
        "term": "じょうず「な」（上手な）",
        "meaning": "Giỏi, khéo"
      },
      {
        "term": "へた「な」（下手な）",
        "meaning": "Kém"
      },
      {
        "term": "のみもの（飲み物）",
        "meaning": "Đồ uống"
      },
      {
        "term": "りょうり（料理）をします",
        "meaning": "Món ăn, việc nấu ăn"
      },
      {
        "term": "スポーツ（をします）",
        "meaning": "(Chơi) Thể thao"
      },
      {
        "term": "やきゅう（野球）をします",
        "meaning": "(Chơi) Bóng chày"
      },
      {
        "term": "ダンス（をします）",
        "meaning": "Nhảy, khiêu vũ"
      },
      {
        "term": "りょこう（旅行）をします",
        "meaning": "(Đi) Du lịch"
      },
      {
        "term": "おんがく（音楽）",
        "meaning": "Âm nhạc"
      },
      {
        "term": "うた（歌）",
        "meaning": "Bài hát"
      },
      {
        "term": "クラシック",
        "meaning": "Nhạc cổ điển"
      },
      {
        "term": "ジャズ",
        "meaning": "Nhạc jazz"
      },
      {
        "term": "コンサート",
        "meaning": "Buổi hòa nhạc"
      },
      {
        "term": "カラオケ",
        "meaning": "Karaoke"
      },
      {
        "term": "かぶき（歌舞伎）",
        "meaning": "Kịch Kabuki"
      },
      {
        "term": "え（絵）",
        "meaning": "Tranh, hội họa"
      },
      {
        "term": "じ（字）",
        "meaning": "Chữ"
      },
      {
        "term": "こまかいおかね（細かいお金）",
        "meaning": "Tiền lẻ"
      },
      {
        "term": "チケット",
        "meaning": "Vé"
      },
      {
        "term": "じかん（時間）",
        "meaning": "Thời gian"
      },
      {
        "term": "ようじ（用事）",
        "meaning": "Việc bận"
      },
      {
        "term": "やくそく（約束）（をします）",
        "meaning": "Cuộc hẹn/ lời hứa"
      },
      {
        "term": "アルバイト（をします）",
        "meaning": "Làm thêm"
      },
      {
        "term": "ごしゅじん（ご主人）",
        "meaning": "Chồng (người ta)"
      },
      {
        "term": "おっと／しゅじん（夫/主人）",
        "meaning": "Chồng (của mình)"
      },
      {
        "term": "おくさん（奥さん）",
        "meaning": "Vợ (người ta)"
      },
      {
        "term": "つま／かない（妻/家内）",
        "meaning": "Vợ (của mình)"
      },
      {
        "term": "こども（子ども）",
        "meaning": "Trẻ em, con cái, con nít"
      },
      {
        "term": "よく",
        "meaning": "Tốt, rõ (chỉ mức độ)"
      },
      {
        "term": "だいたい",
        "meaning": "Đại khái"
      },
      {
        "term": "たくさん",
        "meaning": "Nhiều"
      },
      {
        "term": "すこし（少し）",
        "meaning": "Một ít"
      },
      {
        "term": "ぜんぜん（全然）",
        "meaning": "Hoàn toàn"
      },
      {
        "term": "はやく（早く）",
        "meaning": "Sớm"
      },
      {
        "term": "はやく（速く）",
        "meaning": "Nhanh"
      },
      {
        "term": "ざんねんです［が］（残念です［が］）",
        "meaning": "Tôi xin lỗi, [nhưng...]/ Đáng tiếc là..."
      },
      {
        "term": "だめですか",
        "meaning": "Không được à?"
      },
      {
        "term": "またこんどおねがいします（また今度お願いします）",
        "meaning": "Hẹn anh/ chị lần sau vậy"
      }
    ]
  },
  {
    "id": 10,
    "title": "Tồn tại",
    "words": [
      {
        "term": "あります",
        "meaning": "Có (tồn tại, dùng cho đồ vật)"
      },
      {
        "term": "います",
        "meaning": "Ở (tồn tại, dùng cho người và con vật)"
      },
      {
        "term": "いろいろ（な）",
        "meaning": "Nhiều, đa dạng"
      },
      {
        "term": "おとこのひと（男の人）",
        "meaning": "Người đàn ông"
      },
      {
        "term": "おんなのひと（女の人）",
        "meaning": "Người phụ nữ, người đàn bà"
      },
      {
        "term": "おとこのこ（男の子）",
        "meaning": "Đứa bé trai, cậu con trai"
      },
      {
        "term": "おんなのこ（女の子）",
        "meaning": "Đứa bé gái, cô con gái"
      },
      {
        "term": "いぬ（犬）",
        "meaning": "Chó"
      },
      {
        "term": "ねこ（猫）",
        "meaning": "Mèo"
      },
      {
        "term": "パンダ",
        "meaning": "Gấu trúc"
      },
      {
        "term": "ぞう（象）",
        "meaning": "Voi"
      },
      {
        "term": "き（木）",
        "meaning": "Cây, gỗ"
      },
      {
        "term": "もの",
        "meaning": "Vật, đồ vật"
      },
      {
        "term": "でんち（電池）",
        "meaning": "Pin"
      },
      {
        "term": "はこ（箱）",
        "meaning": "Hộp"
      },
      {
        "term": "スイッチ",
        "meaning": "Công tắc"
      },
      {
        "term": "れいぞうこ（冷蔵庫）",
        "meaning": "Tủ lạnh"
      },
      {
        "term": "テーブル",
        "meaning": "Bàn"
      },
      {
        "term": "ベッド",
        "meaning": "Giường"
      },
      {
        "term": "たな",
        "meaning": "Cái giá, cái kệ"
      },
      {
        "term": "ドア",
        "meaning": "Cửa"
      },
      {
        "term": "まど（窓）",
        "meaning": "Cửa sổ"
      },
      {
        "term": "ポスト",
        "meaning": "Hộp thư, hòm thư"
      },
      {
        "term": "ビル",
        "meaning": "Tòa nhà"
      },
      {
        "term": "ATM",
        "meaning": "Máy rút tiền tự động"
      },
      {
        "term": "コンビニ",
        "meaning": "Cửa hàng tiện lợi"
      },
      {
        "term": "こうえん（公園）",
        "meaning": "Công viên"
      },
      {
        "term": "きっさてん（喫茶店）",
        "meaning": "Quán giải khát"
      },
      {
        "term": "や（～屋）",
        "meaning": "Hiệu ~, cửa hàng ~"
      },
      {
        "term": "のりば（乗り場）",
        "meaning": "Điểm đón taxi, tàu,…"
      },
      {
        "term": "けん（～県）",
        "meaning": "Tỉnh ~"
      },
      {
        "term": "うえ（上）",
        "meaning": "Trên"
      },
      {
        "term": "した（下）",
        "meaning": "Dưới"
      },
      {
        "term": "まえ（前）",
        "meaning": "Trước"
      },
      {
        "term": "うしろ（後ろ）",
        "meaning": "Sau"
      },
      {
        "term": "みぎ（右）",
        "meaning": "Phải"
      },
      {
        "term": "ひだり（左）",
        "meaning": "Trái"
      },
      {
        "term": "なか（中）",
        "meaning": "Trong"
      },
      {
        "term": "そと（外）",
        "meaning": "Ngoài"
      },
      {
        "term": "となり（隣）",
        "meaning": "Kế bên"
      },
      {
        "term": "ちかく（近く）",
        "meaning": "Gần"
      },
      {
        "term": "あいだ（間）",
        "meaning": "Ở giữa"
      },
      {
        "term": "～や～［など］",
        "meaning": "~ và, ~ [v.v.] / ~ nào là ~ nào là"
      }
    ]
  },
  {
    "id": 11,
    "title": "Gia đình",
    "words": [
      {
        "term": "います",
        "meaning": "Có, ở （「こども」がいます：Có con／「にほんにいます」：Ở Nhật Bản）"
      },
      {
        "term": "かかります",
        "meaning": "Tốn （「じかんが」かかります：Tốn thời gian）"
      },
      {
        "term": "やすみます（休みます）",
        "meaning": "Nghỉ （「かいしゃを」やすみます：Nghỉ công ty）"
      },
      {
        "term": "りょうしん（両親）",
        "meaning": "Cha mẹ"
      },
      {
        "term": "きょうだい（兄弟）",
        "meaning": "Anh em"
      },
      {
        "term": "あに（兄）／おにいさん（お兄さん）",
        "meaning": "Anh trai/ anh (người khác)"
      },
      {
        "term": "あね（姉）／おねえさん（お姉さん）",
        "meaning": "Chị gái/ chị (người khác)"
      },
      {
        "term": "おとうと（弟）／おとうとさん（弟さん）",
        "meaning": "Em trai/ Em trai (người khác)"
      },
      {
        "term": "いもうと（妹）／いもうとさん（妹さん）",
        "meaning": "Em gái/ Em gái (người khác)"
      },
      {
        "term": "そふ（祖父）",
        "meaning": "Ông"
      },
      {
        "term": "そぼ（祖母）",
        "meaning": "Bà"
      },
      {
        "term": "そふぼ（祖父母）",
        "meaning": "Ông bà"
      },
      {
        "term": "りんご",
        "meaning": "Táo"
      },
      {
        "term": "みかん",
        "meaning": "Quýt"
      },
      {
        "term": "サンドイッチ",
        "meaning": "Sandwich"
      },
      {
        "term": "カレー「ライス」",
        "meaning": "Cơm Cà ri"
      },
      {
        "term": "アイスクリーム",
        "meaning": "Kem"
      },
      {
        "term": "きって（切手）",
        "meaning": "Tem"
      },
      {
        "term": "はがき",
        "meaning": "Bưu thiếp"
      },
      {
        "term": "ふうとう（封筒）",
        "meaning": "Phong bì"
      },
      {
        "term": "がいこく（外国）",
        "meaning": "Nước ngoài"
      },
      {
        "term": "りゅうがくせい（留学生）",
        "meaning": "Du học sinh"
      },
      {
        "term": "クラス",
        "meaning": "Lớp học"
      },
      {
        "term": "ぜんぶで（全部で）",
        "meaning": "Tổng cộng"
      },
      {
        "term": "みんな",
        "meaning": "Mọi người, tất cả"
      },
      {
        "term": "～だけ",
        "meaning": "Chỉ ~"
      },
      {
        "term": "～じかん（時間）",
        "meaning": "~ tiếng"
      },
      {
        "term": "～にち（日）",
        "meaning": "ngày ~"
      },
      {
        "term": "～しゅうかん（週間）",
        "meaning": "~ tuần"
      },
      {
        "term": "～かげつ（～ヶ月）",
        "meaning": "~ tháng"
      },
      {
        "term": "～ねん（～年）",
        "meaning": "năm ~"
      },
      {
        "term": "ぐらい",
        "meaning": "Khoảng"
      },
      {
        "term": "どのぐらい",
        "meaning": "Bao lâu?"
      }
    ]
  },
  {
    "id": 12,
    "title": "Lễ hội",
    "words": [
      {
        "term": "かんたん（な）（簡単な）",
        "meaning": "Đơn giản"
      },
      {
        "term": "ふくざつ（な）（複雑な）",
        "meaning": "Phức tạp"
      },
      {
        "term": "ちかい（近い）",
        "meaning": "Gần"
      },
      {
        "term": "とおい（遠い）",
        "meaning": "Xa"
      },
      {
        "term": "はやい（早い）",
        "meaning": "Sớm"
      },
      {
        "term": "はやい（速い）",
        "meaning": "Nhanh"
      },
      {
        "term": "おそい（遅い）",
        "meaning": "Chậm, trễ"
      },
      {
        "term": "おおい（多い）",
        "meaning": "Nhiều ／「ひとが」おおい — Đông người"
      },
      {
        "term": "すくない（少ない）",
        "meaning": "Ít ／「ひとが」すくない — Ít, vắng người"
      },
      {
        "term": "あたたかい",
        "meaning": "Ấm áp"
      },
      {
        "term": "すずしい（涼しい）",
        "meaning": "Mát"
      },
      {
        "term": "おもい（重い）",
        "meaning": "Nặng"
      },
      {
        "term": "かるい（軽い）",
        "meaning": "Nhẹ"
      },
      {
        "term": "すっぱい（酸っぱい）",
        "meaning": "Chua"
      },
      {
        "term": "からい（辛い）",
        "meaning": "Cay"
      },
      {
        "term": "しおからい（塩辛い）",
        "meaning": "Mặn"
      },
      {
        "term": "あまい（甘い）",
        "meaning": "Ngọt"
      },
      {
        "term": "きせつ（季節）",
        "meaning": "Mùa"
      },
      {
        "term": "はる（春）",
        "meaning": "Xuân"
      },
      {
        "term": "なつ（夏）",
        "meaning": "Hạ"
      },
      {
        "term": "あき（秋）",
        "meaning": "Thu"
      },
      {
        "term": "ふゆ（冬）",
        "meaning": "Đông"
      },
      {
        "term": "てんき（天気）",
        "meaning": "Thời tiết"
      },
      {
        "term": "あめ（雨）",
        "meaning": "Mưa"
      },
      {
        "term": "ゆき（雪）",
        "meaning": "Tuyết"
      },
      {
        "term": "くもり（曇り）",
        "meaning": "Mây"
      },
      {
        "term": "かぜ（風）",
        "meaning": "Gió"
      },
      {
        "term": "はれ（晴れ）",
        "meaning": "Nắng"
      },
      {
        "term": "ホテル",
        "meaning": "Khách sạn"
      },
      {
        "term": "くうこう（空港）",
        "meaning": "Sân bay"
      },
      {
        "term": "うみ（海）",
        "meaning": "Biển"
      },
      {
        "term": "せかい（世界）",
        "meaning": "Thế giới"
      },
      {
        "term": "パーティー（をします）",
        "meaning": "(Mở, tổ chức) tiệc"
      },
      {
        "term": "おまつり（お祭り）",
        "meaning": "Lễ hội"
      },
      {
        "term": "いけばな（生け花）",
        "meaning": "Nghệ thuật cắm hoa"
      },
      {
        "term": "すきやき（すき焼き）",
        "meaning": "Lẩu sukiyaki"
      },
      {
        "term": "さしみ（刺身）",
        "meaning": "Sashimi (gỏi cá sống)"
      },
      {
        "term": "おすし",
        "meaning": "Sushi"
      },
      {
        "term": "てんぷら（天ぷら）",
        "meaning": "Tempura"
      },
      {
        "term": "ぶたにく（豚肉）",
        "meaning": "Thịt heo"
      },
      {
        "term": "とりにく（鶏肉）",
        "meaning": "Thịt gà"
      },
      {
        "term": "ぎゅうにく（牛肉）",
        "meaning": "Thịt bò"
      },
      {
        "term": "レモン",
        "meaning": "Chanh"
      },
      {
        "term": "もみじ",
        "meaning": "Lá đỏ"
      },
      {
        "term": "どちら",
        "meaning": "Cái nào?"
      },
      {
        "term": "どちらも",
        "meaning": "Cái nào cũng"
      },
      {
        "term": "いちばん（一番）",
        "meaning": "Nhất"
      },
      {
        "term": "ずっと",
        "meaning": "Suốt, (hơn) hẳn (so sánh)"
      },
      {
        "term": "はじめて（初めて）",
        "meaning": "Lần đầu tiên"
      }
    ]
  },
  {
    "id": 13,
    "title": "Động từ",
    "words": [
      {
        "term": "あそびます（遊びます）",
        "meaning": "Chơi"
      },
      {
        "term": "およぎます（泳ぎます）",
        "meaning": "Bơi"
      },
      {
        "term": "むかえます",
        "meaning": "Đón （子どもをむかえます：Đón con）"
      },
      {
        "term": "つかれます（疲れます）",
        "meaning": "Mệt"
      },
      {
        "term": "けっこんします（結婚します）",
        "meaning": "Kết hôn"
      },
      {
        "term": "かわきます（乾きます）",
        "meaning": "Khát （のどがかわきます）"
      },
      {
        "term": "すきます",
        "meaning": "Đói （おなかがすきます）"
      },
      {
        "term": "かいものします（買い物します）",
        "meaning": "Mua sắm"
      },
      {
        "term": "しょくじします（食事します）",
        "meaning": "Ăn cơm, dùng bữa"
      },
      {
        "term": "さんぽします（散歩します）",
        "meaning": "Đi dạo, tản bộ （公園をさんぽします）"
      },
      {
        "term": "たいへん（な）（大変な）",
        "meaning": "Vất vả, khó khăn"
      },
      {
        "term": "ほしい（欲しい）",
        "meaning": "Muốn"
      },
      {
        "term": "ひろい（広い）",
        "meaning": "Rộng"
      },
      {
        "term": "せまい（狭い）",
        "meaning": "Chật, hẹp"
      },
      {
        "term": "プール",
        "meaning": "Bể bơi"
      },
      {
        "term": "かわ（川）",
        "meaning": "Sông"
      },
      {
        "term": "つり「をします」（釣り）",
        "meaning": "Câu cá"
      },
      {
        "term": "スキー「をします」",
        "meaning": "Trượt tuyết"
      },
      {
        "term": "しゅうまつ（週末）",
        "meaning": "Cuối tuần"
      },
      {
        "term": "「お」しょうがつ（「お」正月）",
        "meaning": "Tết"
      },
      {
        "term": "～ごろ",
        "meaning": "Khoảng ~ (thời gian)"
      },
      {
        "term": "なにか（何か）",
        "meaning": "Cái gì đó?"
      },
      {
        "term": "どこか",
        "meaning": "Đâu đó?, chỗ nào đó?"
      },
      {
        "term": "そうしましょう",
        "meaning": "Nhất trí, hãy làm như vậy đi"
      }
    ]
  },
  {
    "id": 14,
    "title": "Động từ",
    "words": [
      {
        "term": "つけます",
        "meaning": "Bật （でんきをつけます：Bật điện）"
      },
      {
        "term": "けします（消します）",
        "meaning": "Tắt （でんきをけします：Tắt điện）"
      },
      {
        "term": "あけます（開けます）",
        "meaning": "Mở （ドアをあけます）"
      },
      {
        "term": "しめます（閉めます）",
        "meaning": "Đóng （ドアをしめます）"
      },
      {
        "term": "かけます",
        "meaning": "Khóa （かぎをかけます）"
      },
      {
        "term": "いそぎます（急ぎます）",
        "meaning": "Vội, gấp"
      },
      {
        "term": "まちます（待ちます）",
        "meaning": "Chờ （かのじょをまちます）"
      },
      {
        "term": "もちます（持ちます）",
        "meaning": "Mang, cầm （にもつをもちます）"
      },
      {
        "term": "とります（取ります）",
        "meaning": "Lấy （しおをとります）"
      },
      {
        "term": "てつだいます（手伝います）",
        "meaning": "Giúp đỡ （しごとをてつだいます）"
      },
      {
        "term": "よびます（呼びます）",
        "meaning": "Gọi （なまえをよびます）"
      },
      {
        "term": "はなします（話します）",
        "meaning": "Nói chuyện （ともだちとはなします）"
      },
      {
        "term": "つかいます（使います）",
        "meaning": "Sử dụng （ちずをつかいます）"
      },
      {
        "term": "とめます（止めます）",
        "meaning": "Dừng （くるまをとめます）"
      },
      {
        "term": "みせます（見せます）",
        "meaning": "Cho xem （パスポートをみせます）"
      },
      {
        "term": "おしえます（教えます）",
        "meaning": "Nói, cho biết （じゅうしょをおしえます）"
      },
      {
        "term": "すわります（座ります）",
        "meaning": "Ngồi （いすにすわります）"
      },
      {
        "term": "たちます（立ちます）",
        "meaning": "Đứng dậy"
      },
      {
        "term": "はいります（入ります）",
        "meaning": "Vào （きっさてんにはいります）"
      },
      {
        "term": "でます（出ます）",
        "meaning": "Ra （きっさてんをでます）"
      },
      {
        "term": "ふります（降ります）",
        "meaning": "Rơi （あめがふります）"
      },
      {
        "term": "コピーします",
        "meaning": "Copy, photo"
      },
      {
        "term": "でんき（電気）",
        "meaning": "Điện, đèn điện"
      },
      {
        "term": "エアコン",
        "meaning": "Máy lạnh"
      },
      {
        "term": "パスポート",
        "meaning": "Hộ chiếu"
      },
      {
        "term": "なまえ（名前）",
        "meaning": "Tên"
      },
      {
        "term": "じゅうしょ（住所）",
        "meaning": "Địa chỉ"
      },
      {
        "term": "ちず（地図）",
        "meaning": "Bản đồ"
      },
      {
        "term": "しお（塩）",
        "meaning": "Muối"
      },
      {
        "term": "さとう（砂糖）",
        "meaning": "Đường"
      },
      {
        "term": "もんだい（問題）",
        "meaning": "Câu hỏi/ vấn đề"
      },
      {
        "term": "こたえ（答）",
        "meaning": "Câu trả lời"
      },
      {
        "term": "おつり",
        "meaning": "Tiền thừa, tiền thối lại"
      },
      {
        "term": "～かた（方）",
        "meaning": "Cách （よみかた：Cách đọc／かきかた：Cách viết）"
      },
      {
        "term": "まっすぐ",
        "meaning": "Thẳng"
      },
      {
        "term": "あとで（後で）",
        "meaning": "Sau"
      },
      {
        "term": "すぐ",
        "meaning": "Ngay lập tức"
      },
      {
        "term": "また",
        "meaning": "Lại"
      },
      {
        "term": "ゆっくり",
        "meaning": "Chậm lại, thong thả, thoải mái"
      },
      {
        "term": "もうすこし（もう少し）",
        "meaning": "Thêm một chút nữa"
      },
      {
        "term": "もう～",
        "meaning": "Thêm ~"
      }
    ]
  },
  {
    "id": 15,
    "title": "Danh từ",
    "words": [
      {
        "term": "おきます（置きます）",
        "meaning": "Đặt, để"
      },
      {
        "term": "つくります",
        "meaning": "Làm, sản xuất, chế tạo"
      },
      {
        "term": "うります（売ります）",
        "meaning": "Bán"
      },
      {
        "term": "しります（知ります）",
        "meaning": "Biết"
      },
      {
        "term": "（Nに）すみます（住みます）",
        "meaning": "Sống, ở"
      },
      {
        "term": "けんきゅうします（研究します）",
        "meaning": "Nghiên cứu"
      },
      {
        "term": "しりょう（資料）",
        "meaning": "Tài liệu"
      },
      {
        "term": "カタログ",
        "meaning": "Ca ta lô, catalog"
      },
      {
        "term": "じこくひょう（時刻表）",
        "meaning": "Bảng giờ tàu chạy"
      },
      {
        "term": "ふく（服）",
        "meaning": "Quần áo"
      },
      {
        "term": "ソフト",
        "meaning": "Phần mềm"
      },
      {
        "term": "でんしじしょ（電子辞書）",
        "meaning": "Kim từ điển"
      },
      {
        "term": "せいひん（製品）",
        "meaning": "Sản phẩm"
      },
      {
        "term": "けいざい（経済）",
        "meaning": "Kinh tế"
      },
      {
        "term": "しやくしょ（市役所）",
        "meaning": "Tòa thị chính"
      },
      {
        "term": "こうこう（高校）",
        "meaning": "Trường cấp 3"
      },
      {
        "term": "はいしゃ（歯医者）",
        "meaning": "Nha sĩ"
      },
      {
        "term": "どくしん（独身）",
        "meaning": "Độc thân"
      }
    ]
  },
  {
    "id": 16,
    "title": "Cơ thể con người",
    "words": [
      {
        "term": "「電車に」のります",
        "meaning": "Đi, lên (tàu)"
      },
      {
        "term": "「電車を」おります",
        "meaning": "Xuống (tàu)"
      },
      {
        "term": "乗り換えます",
        "meaning": "Chuyển, đổi (tàu)"
      },
      {
        "term": "「シャワーを」浴びます",
        "meaning": "Tắm (vòi hoa sen)"
      },
      {
        "term": "「カバンに」入れます",
        "meaning": "Cho vào (túi xách)"
      },
      {
        "term": "「資料を」出します",
        "meaning": "Lấy ra, đưa ra, gửi (tài liệu)"
      },
      {
        "term": "「お金を」下ろします",
        "meaning": "Rút (tiền)"
      },
      {
        "term": "「大学に」入ります",
        "meaning": "Vào (đại học), nhập học"
      },
      {
        "term": "「大学を」出ます",
        "meaning": "Ra, tốt nghiệp (đại học)"
      },
      {
        "term": "「ボタンを」押します",
        "meaning": "Bấm, ấn (nút)"
      },
      {
        "term": "「会議を」始めます",
        "meaning": "Bắt đầu (cuộc họp)"
      },
      {
        "term": "見学します",
        "meaning": "Tham quan kiến tập"
      },
      {
        "term": "電話します",
        "meaning": "Gọi điện thoại"
      },
      {
        "term": "わかい（若い）",
        "meaning": "Trẻ"
      },
      {
        "term": "ながい（長い）",
        "meaning": "Dài"
      },
      {
        "term": "みじかい（短い）",
        "meaning": "Ngắn"
      },
      {
        "term": "あかるい（明るい）",
        "meaning": "Sáng"
      },
      {
        "term": "くらい（暗い）",
        "meaning": "Tối"
      },
      {
        "term": "からだ（体）",
        "meaning": "Cơ thể"
      },
      {
        "term": "あたま（頭）",
        "meaning": "Đầu"
      },
      {
        "term": "かみ（髪）",
        "meaning": "Tóc"
      },
      {
        "term": "かお（顔）",
        "meaning": "Mặt"
      },
      {
        "term": "め（目）",
        "meaning": "Mắt"
      },
      {
        "term": "みみ（耳）",
        "meaning": "Tai"
      },
      {
        "term": "はな（鼻）",
        "meaning": "Mũi"
      },
      {
        "term": "くち（口）",
        "meaning": "Miệng"
      },
      {
        "term": "は（歯）",
        "meaning": "Răng"
      },
      {
        "term": "おなか（お腹）",
        "meaning": "Bụng"
      },
      {
        "term": "あし（足）",
        "meaning": "Chân"
      },
      {
        "term": "せ（背）",
        "meaning": "Chiều cao (cơ thể)"
      },
      {
        "term": "サービス",
        "meaning": "Dịch vụ"
      },
      {
        "term": "ジョギング（をします）",
        "meaning": "Chạy bộ"
      },
      {
        "term": "シャワー",
        "meaning": "Vòi hoa sen"
      },
      {
        "term": "みどり（緑）",
        "meaning": "Màu xanh lá cây, cây xanh"
      },
      {
        "term": "「お」てら（寺）",
        "meaning": "Chùa"
      },
      {
        "term": "じんじゃ（神社）",
        "meaning": "Đền thờ Thần đạo"
      },
      {
        "term": "ボタン",
        "meaning": "Nút"
      },
      {
        "term": "キャッシュカード",
        "meaning": "Thẻ rút tiền, thẻ ATM"
      },
      {
        "term": "まず",
        "meaning": "Trước tiên, đầu tiên"
      },
      {
        "term": "つぎ",
        "meaning": "Tiếp theo, sau đó"
      },
      {
        "term": "すごいですね",
        "meaning": "Tuyệt vời, giỏi quá đi, ghê thật đấy"
      },
      {
        "term": "「いいえ、」まだまだです",
        "meaning": "Không, tôi còn phải cố gắng nhiều nữa"
      }
    ]
  },
  {
    "id": 17,
    "title": "Động từ",
    "words": [
      {
        "term": "おぼえます（覚えます）",
        "meaning": "Nhớ"
      },
      {
        "term": "わすれます（忘れます）",
        "meaning": "Quên"
      },
      {
        "term": "なくします",
        "meaning": "Làm mất, đánh mất"
      },
      {
        "term": "はらいます（払います）",
        "meaning": "Trả tiền"
      },
      {
        "term": "かえします（返します）",
        "meaning": "Trả lại"
      },
      {
        "term": "でかけます（出かけます）",
        "meaning": "Ra ngoài"
      },
      {
        "term": "ぬぎます（脱ぎます）",
        "meaning": "Cởi (quần áo, giầy…)"
      },
      {
        "term": "もっていきます（持っていきます）",
        "meaning": "Mang đi, mang theo"
      },
      {
        "term": "もってきます（持ってきます）",
        "meaning": "Mang đến"
      },
      {
        "term": "しんぱいします（心配します）",
        "meaning": "Lo lắng"
      },
      {
        "term": "ざんぎょうします（残業します）",
        "meaning": "Làm thêm giờ, tăng ca"
      },
      {
        "term": "しゅっちょうします（出張します）",
        "meaning": "Đi công tác"
      },
      {
        "term": "「おふろに」はいります",
        "meaning": "Tắm bồn"
      },
      {
        "term": "たいせつ「な」（大切）",
        "meaning": "Quan trọng, quý giá"
      },
      {
        "term": "だいじょうぶ「な」（大丈夫）",
        "meaning": "Không sao, không vấn đề gì"
      },
      {
        "term": "あぶない（危ない）",
        "meaning": "Nguy hiểm"
      },
      {
        "term": "あたまがいたい（頭が痛い）",
        "meaning": "Đau đầu"
      },
      {
        "term": "きんえん（禁煙）",
        "meaning": "Cấm hút thuốc"
      },
      {
        "term": "けんこう（健康）",
        "meaning": "Sức khỏe"
      },
      {
        "term": "ほけんしょう（保険証）",
        "meaning": "Bảo hiểm （「健康」保険証：Bảo hiểm y tế）"
      },
      {
        "term": "ねつ（熱）",
        "meaning": "Sốt"
      },
      {
        "term": "びょうき（病気）",
        "meaning": "Bệnh"
      },
      {
        "term": "かぜ",
        "meaning": "Bị cảm"
      },
      {
        "term": "くすり（薬）",
        "meaning": "Thuốc"
      },
      {
        "term": "うわぎ（上着）",
        "meaning": "Áo khoác"
      },
      {
        "term": "したぎ（下着）",
        "meaning": "Quần áo lót"
      },
      {
        "term": "2、3～（2、3日）",
        "meaning": "2,3 ~ (2, 3 ngày)"
      },
      {
        "term": "～までに",
        "meaning": "Trước ~, cho đến trước ~ (giới hạn thời gian)"
      },
      {
        "term": "ですから",
        "meaning": "Vì thế, vì vậy, do đó"
      },
      {
        "term": "どうしましたか",
        "meaning": "Anh/chị bị làm sao?, Có vấn đề gì không"
      },
      {
        "term": "おだいじに（お大事に）",
        "meaning": "Giữ gìn sức khỏe nha, mau khỏi bệnh nha."
      }
    ]
  },
  {
    "id": 18,
    "title": "Sở thích",
    "words": [
      {
        "term": "できます",
        "meaning": "Có thể"
      },
      {
        "term": "あらいます（洗います）",
        "meaning": "Rửa"
      },
      {
        "term": "［ピアノ、ギター、…を］ひきます",
        "meaning": "Chơi (piano, guitar,...)"
      },
      {
        "term": "うたいます（歌います）",
        "meaning": "Hát"
      },
      {
        "term": "あつめます（集めます）",
        "meaning": "Sưu tầm, sưu tập"
      },
      {
        "term": "すてます（捨てます）",
        "meaning": "Vứt, bỏ, bỏ đi"
      },
      {
        "term": "かえます（換えます）",
        "meaning": "Đổi, trao đổi"
      },
      {
        "term": "うんてんします（運転します）",
        "meaning": "Lái"
      },
      {
        "term": "よやくします（予約します）",
        "meaning": "Đặt chỗ, đặt trước"
      },
      {
        "term": "ピアノ",
        "meaning": "Đàn Piano"
      },
      {
        "term": "げんきん（現金）",
        "meaning": "Tiền mặt"
      },
      {
        "term": "しゅみ（趣味）",
        "meaning": "Sở thích"
      },
      {
        "term": "にっき（日記）",
        "meaning": "Nhật ký"
      },
      {
        "term": "お祈りをします",
        "meaning": "Cầu nguyện"
      },
      {
        "term": "かちょう（課長）",
        "meaning": "Trưởng bộ phận, tổ trưởng"
      },
      {
        "term": "ぶちょう（部長）",
        "meaning": "Trưởng phòng"
      },
      {
        "term": "しゃちょう（社長）",
        "meaning": "Giám đốc"
      },
      {
        "term": "どうぶつ（動物）",
        "meaning": "Động vật"
      },
      {
        "term": "うま（馬）",
        "meaning": "Ngựa"
      },
      {
        "term": "インターネット",
        "meaning": "Internet"
      },
      {
        "term": "とくに（特に）",
        "meaning": "Đặc biệt là"
      },
      {
        "term": "なかなか",
        "meaning": "Mãi mà, khó mà"
      },
      {
        "term": "ぜひ",
        "meaning": "Nhất định"
      }
    ]
  },
  {
    "id": 19,
    "title": "Du lịch 1",
    "words": [
      {
        "term": "「やまに」のぼります",
        "meaning": "Leo (núi), lên"
      },
      {
        "term": "「ホテルに」とまります",
        "meaning": "Trọ (ở khách sạn)"
      },
      {
        "term": "そうじします（掃除します）",
        "meaning": "Dọn dẹp"
      },
      {
        "term": "せんたくします（洗濯します）",
        "meaning": "Giặt đồ"
      },
      {
        "term": "なります",
        "meaning": "Trở thành, trở nên"
      },
      {
        "term": "れんしゅうします（練習します）",
        "meaning": "Luyện tập"
      },
      {
        "term": "ねむい（眠い）",
        "meaning": "Buồn ngủ"
      },
      {
        "term": "つよい（強い）",
        "meaning": "Mạnh"
      },
      {
        "term": "よわい（弱い）",
        "meaning": "Yếu"
      },
      {
        "term": "むり（な）",
        "meaning": "Quá sức, không thể"
      },
      {
        "term": "からだにいい（体にいい）",
        "meaning": "Tốt cho sức khỏe"
      },
      {
        "term": "ゴルフ",
        "meaning": "Gôn"
      },
      {
        "term": "ホームステイ",
        "meaning": "Homestay"
      },
      {
        "term": "すもう（相撲）",
        "meaning": "Sumo"
      },
      {
        "term": "おちゃ（お茶）",
        "meaning": "Trà, trà đạo"
      },
      {
        "term": "ちょうし（調子）",
        "meaning": "Tình trạng, trạng thái （ちょうしがいい：Tốt, khỏe／ちょうしがわるい：Xấu, không khỏe）"
      },
      {
        "term": "ダイエット",
        "meaning": "Ăn kiêng, ăn chế độ giảm cân"
      },
      {
        "term": "いちども～ません（一度も～ません）",
        "meaning": "Chưa lần nào, chưa bao giờ"
      },
      {
        "term": "いちど（一度）",
        "meaning": "Một lần"
      },
      {
        "term": "だんだん",
        "meaning": "Dần dần"
      },
      {
        "term": "もうすぐ",
        "meaning": "Sắp, sắp sửa"
      },
      {
        "term": "でも",
        "meaning": "Nhưng mà"
      },
      {
        "term": "おかげさまで",
        "meaning": "Nhờ ơn/ Ơn trời"
      },
      {
        "term": "かんぱい（乾杯）",
        "meaning": "Cạn ly/ nâng chén"
      }
    ]
  },
  {
    "id": 20,
    "title": "Du lịch 2",
    "words": [
      {
        "term": "「ビザが」いります",
        "meaning": "Cần (thị thực/visa)"
      },
      {
        "term": "しらべます（調べます）",
        "meaning": "Tìm hiểu, điều tra, kiểm tra"
      },
      {
        "term": "しゅうりします（修理します）",
        "meaning": "Sửa chữa, tu sửa"
      },
      {
        "term": "ことば（言葉）",
        "meaning": "Ngôn ngữ/ từ vựng"
      },
      {
        "term": "きもの（着物）",
        "meaning": "Kimono"
      },
      {
        "term": "ビザ",
        "meaning": "Thị thực/ visa"
      },
      {
        "term": "はじめ（初め）",
        "meaning": "Ban đầu, đầu tiên"
      },
      {
        "term": "おわり（終わり）",
        "meaning": "Kết thúc, hết phim"
      },
      {
        "term": "こっち",
        "meaning": "Phía này, chỗ này"
      },
      {
        "term": "そっち",
        "meaning": "Phía đó, chỗ đó"
      },
      {
        "term": "あっち",
        "meaning": "Phía kia, chỗ kia"
      },
      {
        "term": "どっち",
        "meaning": "Cái nào (giữa 2 cái)?, phía nào?, đâu?"
      },
      {
        "term": "みんなで",
        "meaning": "Mọi người cùng"
      },
      {
        "term": "～けど",
        "meaning": "~, nhưng (thân mật của が)"
      },
      {
        "term": "ぼく（僕）",
        "meaning": "Tôi, tớ (nam giới)"
      },
      {
        "term": "きみ（君）",
        "meaning": "Cậu, bạn"
      },
      {
        "term": "～くん",
        "meaning": "Dùng sau tên người ngang hàng/ nhỏ tuổi hơn"
      },
      {
        "term": "よかったら",
        "meaning": "Nếu anh/chị thích thì…"
      },
      {
        "term": "おなかがいっぱい",
        "meaning": "No (bụng)"
      }
    ]
  },
  {
    "id": 21,
    "title": "Cuộc sống 1",
    "words": [
      {
        "term": "おもいます（思います）",
        "meaning": "Nghĩ"
      },
      {
        "term": "いいます（言います）",
        "meaning": "Nói"
      },
      {
        "term": "まけます（負けます）",
        "meaning": "Thua"
      },
      {
        "term": "かちます（勝ちます）",
        "meaning": "Thắng"
      },
      {
        "term": "「お祭りが」あります",
        "meaning": "[Lễ hội] được tổ chức"
      },
      {
        "term": "「会社に」役に立ちます",
        "meaning": "Có ích cho [công ty]"
      },
      {
        "term": "うごきます（動きます）",
        "meaning": "Chuyển động, chạy"
      },
      {
        "term": "「会社を」やめます",
        "meaning": "Bỏ, thôi việc (ở công ty)"
      },
      {
        "term": "「車に」気をつけます",
        "meaning": "Chú ý, cẩn thận (xe)"
      },
      {
        "term": "りゅうがくします（留学します）",
        "meaning": "Du học"
      },
      {
        "term": "むだ（な）",
        "meaning": "Lãng phí, vô ích"
      },
      {
        "term": "ふべん（な）（不便）",
        "meaning": "Bất tiện"
      },
      {
        "term": "ほんとう（本当）",
        "meaning": "Sự thật"
      },
      {
        "term": "うそ",
        "meaning": "Sự giả dối"
      },
      {
        "term": "じどうしゃ（自動車）",
        "meaning": "Ô tô, xe hơi"
      },
      {
        "term": "こうつう（交通）",
        "meaning": "Giao thông"
      },
      {
        "term": "ぶっか（物価）",
        "meaning": "Vật giá"
      },
      {
        "term": "ほうそう（放送）",
        "meaning": "Phát thanh"
      },
      {
        "term": "ニュース",
        "meaning": "Tin tức"
      },
      {
        "term": "アニメ",
        "meaning": "Phim hoạt hình"
      },
      {
        "term": "まんが（漫画）",
        "meaning": "Truyện tranh"
      },
      {
        "term": "デザイン",
        "meaning": "Thiết kế"
      },
      {
        "term": "ゆめ（夢）",
        "meaning": "Giấc mơ, ước mơ"
      },
      {
        "term": "てんさい（天才）",
        "meaning": "Thiên tài"
      },
      {
        "term": "しあい（試合）",
        "meaning": "Trận đấu"
      },
      {
        "term": "いけん（意見）",
        "meaning": "Ý kiến"
      },
      {
        "term": "はなし（話）",
        "meaning": "Câu chuyện"
      },
      {
        "term": "ちきゅう（地球）",
        "meaning": "Trái đất"
      },
      {
        "term": "つき（月）",
        "meaning": "Mặt trăng"
      },
      {
        "term": "さいきん（最近）",
        "meaning": "Dạo gần đây"
      },
      {
        "term": "たぶん（多分）",
        "meaning": "Chắc, có thể"
      },
      {
        "term": "きっと",
        "meaning": "Chắc chắn, nhất định"
      },
      {
        "term": "ほんとうに（本当に）",
        "meaning": "Thật sự"
      },
      {
        "term": "そんなに",
        "meaning": "(Không) ~ lắm"
      },
      {
        "term": "ひさしぶりです（久しぶりです）",
        "meaning": "Đã lâu không gặp anh/chị"
      },
      {
        "term": "もちろん",
        "meaning": "Tất nhiên, dĩ nhiên"
      },
      {
        "term": "もうかえらないと...（もう帰らないと...）",
        "meaning": "Tôi phải về rồi..."
      }
    ]
  },
  {
    "id": 22,
    "title": "Đồ vật cá nhân",
    "words": [
      {
        "term": "（シャツを）着ます",
        "meaning": "Mặc (áo sơ mi)"
      },
      {
        "term": "（くつ、ズボン、…を）はきます",
        "meaning": "Đi (giầy, vớ, …), mặc (quần, váy, …)"
      },
      {
        "term": "（ぼうしを）かぶります",
        "meaning": "Đội (nón)"
      },
      {
        "term": "（メガネを）かけます",
        "meaning": "Đeo (kính)"
      },
      {
        "term": "（ネクタイを）します",
        "meaning": "Đeo (cà vạt)"
      },
      {
        "term": "（こどもが）うまれます",
        "meaning": "(Đứa trẻ) được sinh ra"
      },
      {
        "term": "コート",
        "meaning": "Áo khoác"
      },
      {
        "term": "セーター",
        "meaning": "Áo len"
      },
      {
        "term": "スーツ",
        "meaning": "Com-le, vét"
      },
      {
        "term": "ぼうし（帽子）",
        "meaning": "Mũ"
      },
      {
        "term": "めがね（眼鏡）",
        "meaning": "Kính"
      },
      {
        "term": "ケーキ",
        "meaning": "Bánh ngọt"
      },
      {
        "term": "「お」べんとう「お」弁当",
        "meaning": "Cơm hộp"
      },
      {
        "term": "ロボット",
        "meaning": "Rô bốt"
      },
      {
        "term": "ユーモア",
        "meaning": "Sự hài hước （ユーモアがあります：Có khiếu hài hước）"
      },
      {
        "term": "つごう（都合）",
        "meaning": "Thời gian thích hợp （つごうがいい：Thuận tiện／つごうがわるい：Không thuận tiện）"
      },
      {
        "term": "よく",
        "meaning": "Thường, hay"
      }
    ]
  },
  {
    "id": 23,
    "title": "Cuộc sống 2",
    "words": [
      {
        "term": "「せんせいに」ききます",
        "meaning": "Hỏi (giáo viên)"
      },
      {
        "term": "まわします（回します）",
        "meaning": "Vặn"
      },
      {
        "term": "ひきます（引きます）",
        "meaning": "Kéo"
      },
      {
        "term": "かえます（変えます）",
        "meaning": "Đổi"
      },
      {
        "term": "「ドアに」さわります",
        "meaning": "Sờ, chạm vào (cái cửa)"
      },
      {
        "term": "「おつりが」でます",
        "meaning": "(Tiền thừa) ra, chạy ra"
      },
      {
        "term": "あるきます（歩きます）",
        "meaning": "Đi bộ"
      },
      {
        "term": "「はしを」わたります",
        "meaning": "Qua, đi qua (cầu)"
      },
      {
        "term": "「みぎへ」まがります",
        "meaning": "Rẽ, quẹo (bên phải)"
      },
      {
        "term": "さびしい（寂しい）",
        "meaning": "Buồn, cô đơn"
      },
      {
        "term": "おゆ（湯）",
        "meaning": "Nước nóng"
      },
      {
        "term": "おと（音）",
        "meaning": "Âm thanh"
      },
      {
        "term": "サイズ",
        "meaning": "Cỡ, kích cỡ"
      },
      {
        "term": "こしょうをします（故障をします）",
        "meaning": "Hỏng, hỏng hóc"
      },
      {
        "term": "みち（道）",
        "meaning": "Đường"
      },
      {
        "term": "こうさてん（交差点）",
        "meaning": "Ngã tư"
      },
      {
        "term": "しんごう（信号）",
        "meaning": "Đèn tín hiệu"
      },
      {
        "term": "かど（角）",
        "meaning": "Góc"
      },
      {
        "term": "はし（橋）",
        "meaning": "Cầu"
      },
      {
        "term": "ちゅうしゃじょう（駐車場）",
        "meaning": "Bãi đỗ xe"
      },
      {
        "term": "たてもの（建物）",
        "meaning": "Toà nhà"
      },
      {
        "term": "なんかいも（何回も）",
        "meaning": "Nhiều lần"
      }
    ]
  },
  {
    "id": 24,
    "title": "Cho tặng",
    "words": [
      {
        "term": "くれます",
        "meaning": "Cho tặng (cho tôi)"
      },
      {
        "term": "なおします（直します）",
        "meaning": "Sửa, chữa"
      },
      {
        "term": "つれていきます（連れて行きます）",
        "meaning": "Dẫn (một ai đó) đi"
      },
      {
        "term": "つれてきます（連れて来ます）",
        "meaning": "Dẫn (một ai đó) đến"
      },
      {
        "term": "「ひとを」おくります",
        "meaning": "Tiễn (một ai đó)"
      },
      {
        "term": "しょうかいします（紹介します）",
        "meaning": "Giới thiệu"
      },
      {
        "term": "あんないします（案内します）",
        "meaning": "Hướng dẫn, giới thiệu, dẫn đường"
      },
      {
        "term": "せつめいします（説明します）",
        "meaning": "Giải thích, trình bày"
      },
      {
        "term": "おじいさん／おじいちゃん",
        "meaning": "Ông nội, ông ngoại, ông (cụ/lão)"
      },
      {
        "term": "おばあさん／おばあちゃん",
        "meaning": "Bà nội, bà ngoại, bà (cụ/lão)"
      },
      {
        "term": "じゅんびをします（準備をします）",
        "meaning": "Chuẩn bị"
      },
      {
        "term": "ひっこしをします（引越しをします）",
        "meaning": "Chuyển nhà"
      },
      {
        "term": "おかし",
        "meaning": "Bánh kẹo"
      },
      {
        "term": "ぜんぶ（全部）",
        "meaning": "Toàn bộ, tất cả"
      },
      {
        "term": "じぶんで（自分で）",
        "meaning": "Tự (mình)"
      },
      {
        "term": "ほかに（他に）",
        "meaning": "Ngoài ra, bên cạnh đó"
      }
    ]
  },
  {
    "id": 25,
    "title": "Cuộc sống 3",
    "words": [
      {
        "term": "かんがえます（考えます）",
        "meaning": "Nghĩ, suy nghĩ"
      },
      {
        "term": "「えきに」つきます",
        "meaning": "Đến (nhà ga)"
      },
      {
        "term": "「としを」とります",
        "meaning": "Có, thêm (tuổi)"
      },
      {
        "term": "たります（足ります）",
        "meaning": "Đủ"
      },
      {
        "term": "いなか（田舎）",
        "meaning": "Quê, nông thôn"
      },
      {
        "term": "チャンス",
        "meaning": "Cơ hội"
      },
      {
        "term": "いちおくえん（一億円）",
        "meaning": "Một trăm triệu (yên)"
      },
      {
        "term": "いみ（意味）",
        "meaning": "Ý nghĩa"
      },
      {
        "term": "てんきん（転勤）",
        "meaning": "Chuyển công tác, chuyển địa điểm làm việc"
      },
      {
        "term": "もし「～たら」",
        "meaning": "Nếu"
      },
      {
        "term": "「色々」お世話になりました",
        "meaning": "Cảm ơn anh/chị đã giúp đỡ tôi rất nhiều"
      },
      {
        "term": "がんばります",
        "meaning": "Cố gắng, cố"
      },
      {
        "term": "どうぞおげんきで（どうぞお元気で）",
        "meaning": "Chúc anh/chị mạnh khỏe. Anh/chị bảo trọng nhé"
      }
    ]
  }
];
